# Generated by Django 4.2.16 on 2024-10-07 21:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="financialreport",
            name="file_hash",
            field=models.CharField(default="", max_length=256),
        ),
    ]
