# Generated by Django 4.2.16 on 2024-10-09 19:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_financialreport_file_hash"),
    ]

    operations = [
        migrations.AddField(
            model_name="financialreport",
            name="file_name",
            field=models.CharField(default="", max_length=256),
        ),
    ]
